import React from "react";
import { useState } from "react";
export default function Privacy(props) {
    return (
        <div className="bg-gray-900 flex flex-col items-center justify-center mx-auto h-screen ">
            <div className="multiline text-white p-5"
            >
                <h1 className="text-4xl font-bold">Privacy Policy</h1>
                At Directory0.org, we value your privacy and are committed to protecting your personal information. This Privacy Policy outlines the types of information we collect, how we use and store that information, and your rights regarding your personal data.

                By using the Website, you agree to the collection and use of information in accordance with this Privacy Policy.

                Information We Collect

                When you use Directory0.org, we may collect the following types of information:

                a. Personal Information: This includes information that can be used to identify you, such as your name and email address. We collect this information when you create an account, subscribe to our newsletter, or otherwise voluntarily provide it to us.

                b. Usage Data: This includes information about your interaction with the Website, such as pages visited, time spent on the site, and other usage patterns. We collect this information using Google Analytics and other similar technologies.

                c. User Content: This includes information you submit to the Website, such as bookmarks, upvotes, and any other data you provide.

                How We Use Your Information

                We use the information we collect for the following purposes:

                a. To provide and maintain the Website and its services;
                b. To personalize your experience on the Website and improve its functionality;
                c. To analyze the Website's performance and usage patterns;
                d. To communicate with you regarding updates, promotions, or other relevant information;
                e. To prevent and detect fraudulent or unauthorized activity; and
                f. To comply with legal obligations and protect the rights and safety of Directory0.org and its users.

                Information Storage and Security

                We take appropriate measures to protect your personal information from unauthorized access, disclosure, or alteration. However, no method of electronic storage or transmission is completely secure, and we cannot guarantee the absolute security of your personal information.

                Your personal information is stored on secure servers and is retained only for as long as necessary to fulfill the purposes for which it was collected, or as required by law.

                Google Analytics

                We use Google Analytics to collect and analyze information about your use of the Website. Google Analytics uses cookies to collect usage data and generate reports on the performance of the Website. The information generated by the cookies about your use of the Website, including your IP address, will be transmitted to and stored by Google on servers in the United States. Google may use this information for the purpose of evaluating your use of the Website, compiling reports on Website activity for us, and providing other services relating to Website activity and internet usage.

                By using the Website, you consent to the processing of data about you by Google in the manner and for the purposes set out above. To learn more about how Google Analytics collects and processes data, please visit: https://www.google.com/policies/privacy/partners/.

                Your Rights

                You have the right to access, correct, update, or delete your personal information at any time. To exercise these rights, please contact us at [email address]. We may require you to verify your identity before fulfilling your request.

                Changes to This Privacy Policy

                We reserve the right to update or modify this Privacy Policy at any time. Any changes will be effective immediately upon posting on the Website. Your continued use of the Website following any changes to the Privacy Policy constitutes your acceptance of those changes.

                Contact Us

                If you have any questions or concerns about this Privacy Policy or our privacy practices, please contact us at [email address].
            </div>
        </div>)
}